project:
  name: terraform-azurerm-automation-demo
  code: 33er45tr
  include:
    - .
  exclude:
    - '**/.terraform/*'
    - '**/node_modules/*'
    - '**/.git/**'

terraform:
  version: 0.14.3
  varFile:
    - default.tfvars
